### ISSUE TITLE
Warnings from adapter

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [frankjoke/ioBroker.bmw#24]
020-05-25 16:36:21.878 - warn: bmw.0 (7719) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!
--
2020-05-25 16:36:22.543 - warn: bmw.0 (7719) Promise failed @ '_tickCallback in internal/process/next_tick.js @68:7' error: { Error: Not exists at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1588:72 at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2999:68) at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93403) at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23) at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49) at process._tickCallback (internal/process/next_tick.js:68:7) [stack]: 'Error: Not exists\n at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1588:72\n at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2999:68)\n at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93403)\n at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)\n at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)\n at process._tickCallback (internal/process/next_tick.js:68:7)', [message]: 'Not exists' }

**Comment by frankjoke** [comment]
Ich weiß dass js-controller 3.x spezifischer sind und bin dabei alle Adapter umzustellen. Wann BMW drankommt kann ich momentan nicht sagen, aber es sollte vor der nächsten JS-controller-Version sein wo sie nicht mehr funktionieren würden!
